# Generated by Django 4.2.1 on 2023-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibration',
            name='frequency',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='vibration',
            name='voltage',
            field=models.IntegerField(default=380),
        ),
    ]
